// Generated by gencpp from file pkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_ADDTWOINTS_H
#define PKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <pkg/AddTwoIntsRequest.h>
#include <pkg/AddTwoIntsResponse.h>


namespace pkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::pkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::pkg::AddTwoInts > {
  static const char* value()
  {
    return "pkg/AddTwoInts";
  }

  static const char* value(const ::pkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::pkg::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::pkg::AddTwoInts > 
template<>
struct MD5Sum< ::pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::AddTwoInts >::value();
  }
  static const char* value(const ::pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::AddTwoIntsRequest> should match 
// service_traits::DataType< ::pkg::AddTwoInts > 
template<>
struct DataType< ::pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::pkg::AddTwoInts >::value();
  }
  static const char* value(const ::pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::pkg::AddTwoInts > 
template<>
struct MD5Sum< ::pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::AddTwoInts >::value();
  }
  static const char* value(const ::pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::AddTwoIntsResponse> should match 
// service_traits::DataType< ::pkg::AddTwoInts > 
template<>
struct DataType< ::pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::pkg::AddTwoInts >::value();
  }
  static const char* value(const ::pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_MESSAGE_ADDTWOINTS_H
